---
- name: add some non-standard repos

  block:
        
    - name: Add nodesource for nodejs/nsm  signing key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add nodesource for nodejs/nsm  repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://deb.nodesource.com/node_16.x {{ansible_distribution_release}} main
        state: present

