---
- name: add some non-standard repos

  block:
        
    - name: Add cloudsmith Erlang signing key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key
        state: present

    - name: Add cloudsmith rabbitmq signing key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key
        state: present

    - name: erlang for rabbitmq repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ansible_distribution_release}} main
        state: present

    - name: erlang rabbitmq-server repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ansible_distribution_release}} main
        state: present

    - name: Add nodesource for nodejs/nsm  signing key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add nodesource for nodejs/nsm  repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://deb.nodesource.com/node_16.x {{ansible_distribution_release}} main
        state: present

